api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Application/Panda/Command'
            - '%kernel.project_dir%/src/Domain/Panda/Model'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    exception_to_status:
        Application\Panda\Exception\PandaNotFoundException: 404
