doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Panda_Model:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Panda/Model'
                prefix: 'Domain\Panda\Model'
                alias: Panda
