parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Application\:
        resource: '../src/Application'
        exclude:
            - '../src/Application/Panda/Command/*'
#            - '../src/Application/Panda/Query/*'
    Infrastructure\:
        resource: '../src/Infrastructure'

    Domain\Panda\PandaRepository: '@Infrastructure\Panda\Repository\PandaRepositoryUsingDoctrine'
